---
- name: Checkout dotfiles repo
  git:
    repo: 'https://github.com/zacsek/dotfiles'
    dest: {{ ansible_user_dir }}/.dotfiles

- name: Symlink all to user
  shell: stow -d {{ ansible_user_dir }}/.dotfiles -t {{ ansible_user_dir }}/ {{ item }}
  with_items:
    - bash
    # - zsh
    - vim
    - nvim
    - git
    # - tmux

# - name: Symlink all to root
#   shell: stow -d {{ ansible_user_dir }}/.dotfiles -t /root/ {{ item }}
#   with_items:
#     - bash
#     - zsh
#     - vim
#     - nvim
#     - git
#     - tmux
