---
- name: Add all PPA repositories
  block:
    - debug: "Adding PPA repo: {{ ppa_source }}"
    - apt_repository:
        repo: "{{ ppa_source }}"
        codename: "{{ ubuntu_codename }}"
        state: present
      become: true
  vars:
    ppa_name: "{{ item.key }}"
    ppa_source: "{{ item.value.source }}"
  loop: "{{ ppa | dict2items }}"

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  register: apt_update_result
  ignore_errors: true

- name: Install PPA packages
  apt:
    name: "{{ ppa | dict2items | map(attribute='key') | list }}"
    state: present
  ignore_errors: true
