---
- name: Install dotfiles prerequisites
  apt:
    name:
      - bash
      - zsh
      - git
      - stow
      - vim
    state: present

- name: Install NeoVim
  include_tasks: install_ppa.yml

- name: Install NvChad
  git:
    repo: https://github.com/NvChad/NvChad
    dest: ~/.config/nvim
    depth: 1

- name: Checkout dotfiles
  git:
    repo: https://github.com/zacsek/dotfiles
    dest: ~/.dotfiles

# - name: Backup all conflicting configurations
#   debug: TODO

- name: Execute stow
  command: stow

