---
- name: Install ASDF prerequisites.
  become: true
  apt:
    name:
      - git
      - curl
      - build-essential
      - libssl-dev
    state: present

- name: Download and install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf

- name: Reload shell configuration
  command: source ~/.bashrc

- name: Install system dependencies for plugins
  become: true
  apt:
    name: "{{ asdf | map(attribute='dependencies') | select('defined') | flatten | unique | sort }}"
    state: present

- name: Install asdf plugin repos
  command: asdf plugin add {{ item.plugin }} {{ item.repo }}
  loop: "{{ asdf }}"

- name: Install latest package for each plugin and set as global
  blockinfile:
    path: ~/.tool-versions
    block: |
      {{ item.plugin }} latest
  loop: "{{ asdf }}"
